// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ-5UUYNxfLiPR01ozx8U_oohl7mhPlMk',
    appId: '1:335763425889:web:642e9bec6a62cc08a17820',
    messagingSenderId: '335763425889',
    projectId: 'pilagenda',
    authDomain: 'pilagenda.firebaseapp.com',
    storageBucket: 'pilagenda.firebasestorage.app',
    measurementId: 'G-GMRWD8XNL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PX_H8oQyq1pC_xQNaCRJp1vbsOskGUA',
    appId: '1:335763425889:android:b69d5792f2eef2baa17820',
    messagingSenderId: '335763425889',
    projectId: 'pilagenda',
    storageBucket: 'pilagenda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvgDD0Z-fboS7stKuasSWWKlSDEwnLMMk',
    appId: '1:335763425889:ios:1f0064af5642390ca17820',
    messagingSenderId: '335763425889',
    projectId: 'pilagenda',
    storageBucket: 'pilagenda.firebasestorage.app',
    iosBundleId: 'com.example.pilagenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvgDD0Z-fboS7stKuasSWWKlSDEwnLMMk',
    appId: '1:335763425889:ios:1f0064af5642390ca17820',
    messagingSenderId: '335763425889',
    projectId: 'pilagenda',
    storageBucket: 'pilagenda.firebasestorage.app',
    iosBundleId: 'com.example.pilagenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ-5UUYNxfLiPR01ozx8U_oohl7mhPlMk',
    appId: '1:335763425889:web:14e46a078b9e43dca17820',
    messagingSenderId: '335763425889',
    projectId: 'pilagenda',
    authDomain: 'pilagenda.firebaseapp.com',
    storageBucket: 'pilagenda.firebasestorage.app',
    measurementId: 'G-13P8GS19NN',
  );
}
